# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trajets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('arrivee_lat', models.FloatField()),
                ('arrivee_lng', models.FloatField()),
                ('arrivee_libelle', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('prix', models.PositiveIntegerField(verbose_name='prix (F CFA)')),
                ('frais_service', models.PositiveIntegerField(default=0, verbose_name='frais de service (F CFA)')),
                ('statut', models.CharField(choices=[('demandee', 'Demandée'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée'), ('annulee', 'Annulée'), ('absent', 'Passager absent'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('litige', 'En litige'), ('cloturee', 'Clôturée')], db_index=True, default='demandee', max_length=10)),
                ('code_depart_sel', models.CharField(blank=True, max_length=64)),
                ('essais_code', models.PositiveSmallIntegerField(default=0)),
                ('acceptee_le', models.DateTimeField(blank=True, null=True)),
                ('refusee_le', models.DateTimeField(blank=True, null=True)),
                ('annulee_le', models.DateTimeField(blank=True, null=True)),
                ('absent_le', models.DateTimeField(blank=True, null=True)),
                ('en_cours_le', models.DateTimeField(blank=True, null=True)),
                ('terminee_le', models.DateTimeField(blank=True, null=True)),
                ('litige_le', models.DateTimeField(blank=True, null=True)),
                ('cloturee_le', models.DateTimeField(blank=True, null=True)),
                ('annulation_tardive', models.BooleanField(default=False)),
                ('absence_lat', models.FloatField(blank=True, null=True)),
                ('absence_lng', models.FloatField(blank=True, null=True)),
                ('annulee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='trajets.pointpriseencharge')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='trajets.trajet')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['-cree_le'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('statut__in', ['demandee', 'acceptee', 'en_cours'])), fields=('trajet', 'passager'), name='une_reservation_active_par_trajet')],
            },
        ),
    ]
