# Generated by Django 5.2.18 on 2026-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='complement_paye',
            field=models.PositiveIntegerField(default=0, verbose_name='complément payé (F CFA)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('flooz', 'Flooz (Moov Africa)'), ('mixx', 'Mixx (Togocom)')], max_length=10),
        ),
    ]
