# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('traite', 'Traité')], default='ouvert', max_length=10)),
                ('resolution', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, choices=[('crediter_conducteur', 'Payer le conducteur'), ('rembourser_passager', 'Rembourser le passager')], max_length=25)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_faits', to=settings.AUTH_USER_MODEL)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements_recus', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='reservations.reservation')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ['-cree_le'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('note', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('commentaire', models.TextField(blank=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_donnees', to=settings.AUTH_USER_MODEL)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_recues', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'note',
                'verbose_name_plural': 'notes',
                'ordering': ['-cree_le'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('reservation', 'auteur'), name='une_note_par_reservation_et_auteur'), models.CheckConstraint(condition=models.Q(('note__gte', 1), ('note__lte', 5)), name='note_entre_1_et_5')],
            },
        ),
    ]
