# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('expire_le', models.DateTimeField()),
                ('essais', models.PositiveSmallIntegerField(default=0)),
                ('utilise', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'code OTP',
                'verbose_name_plural': 'codes OTP',
                'ordering': ['-cree_le'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='nom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, verbose_name='prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', 'Numéro de téléphone invalide (8 à 15 chiffres, + facultatif).')], verbose_name='téléphone'),
        ),
    ]
