# Generated by Django 5.2.18 on 2026-10-09 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode_alter_user_nom_alter_user_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motif_suspension',
            field=models.TextField(blank=True, verbose_name='motif de suspension'),
        ),
    ]
