# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture')], default='voiture', max_length=10, verbose_name='type')),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50, verbose_name='modèle')),
                ('couleur', models.CharField(max_length=30)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('nb_places', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)], verbose_name='nombre de places (conducteur compris)')),
                ('photo', models.ImageField(blank=True, upload_to='vehicules/')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'ordering': ['-cree_le'],
                'abstract': False,
            },
        ),
    ]
