# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LienPartage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('jeton', models.CharField(max_length=64, unique=True)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lien_partage', to='reservations.reservation')),
            ],
            options={
                'verbose_name': 'lien de partage',
                'verbose_name_plural': 'liens de partage',
                'ordering': ['-cree_le'],
                'abstract': False,
            },
        ),
    ]
