# Generated by Django 5.2.18 on 2026-10-08 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('cle', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='clé')),
                ('valeur', models.JSONField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'paramètre',
                'verbose_name_plural': 'paramètres',
                'ordering': ['cle'],
            },
        ),
    ]
