# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('depart_lat', models.FloatField()),
                ('depart_lng', models.FloatField()),
                ('depart_libelle', models.CharField(max_length=255)),
                ('arrivee_lat', models.FloatField()),
                ('arrivee_lng', models.FloatField()),
                ('arrivee_libelle', models.CharField(max_length=255)),
                ('depart_le', models.DateTimeField(db_index=True, verbose_name='départ le')),
                ('places_total', models.PositiveSmallIntegerField()),
                ('places_restantes', models.PositiveSmallIntegerField()),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('prix_place', models.PositiveIntegerField(verbose_name='prix par place (F CFA)')),
                ('statut', models.CharField(choices=[('publie', 'Publié'), ('complet', 'Complet'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], db_index=True, default='publie', max_length=10)),
                ('position_lat', models.FloatField(blank=True, null=True)),
                ('position_lng', models.FloatField(blank=True, null=True)),
                ('position_le', models.DateTimeField(blank=True, null=True)),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets_conduits', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trajets', to='vehicules.vehicule')),
            ],
            options={
                'verbose_name': 'trajet',
                'verbose_name_plural': 'trajets',
                'ordering': ['depart_le'],
            },
        ),
        migrations.CreateModel(
            name='PointPriseEnCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('libelle', models.CharField(max_length=255)),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='trajets.trajet')),
            ],
            options={
                'verbose_name': 'point de prise en charge',
                'verbose_name_plural': 'points de prise en charge',
                'ordering': ['ordre'],
            },
        ),
        migrations.AddConstraint(
            model_name='trajet',
            constraint=models.CheckConstraint(condition=models.Q(('places_restantes__lte', models.F('places_total'))), name='places_restantes_inferieures_au_total'),
        ),
        migrations.AddConstraint(
            model_name='trajet',
            constraint=models.CheckConstraint(condition=models.Q(('places_total__gte', 1)), name='au_moins_une_place'),
        ),
        migrations.AddConstraint(
            model_name='pointpriseencharge',
            constraint=models.UniqueConstraint(fields=('trajet', 'ordre'), name='ordre_unique_par_trajet'),
        ),
    ]
