# Generated by Django 5.2.18 on 2026-10-08 17:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('type', models.CharField(choices=[('recharge', 'Recharge'), ('blocage', 'Blocage'), ('deblocage', 'Déblocage'), ('debit', 'Débit'), ('credit', 'Crédit'), ('retrait', 'Retrait'), ('remboursement', 'Remboursement')], max_length=15)),
                ('montant', models.PositiveIntegerField(verbose_name='montant (F CFA)')),
                ('reference_externe', models.CharField(blank=True, max_length=64)),
                ('statut', models.CharField(choices=[('validee', 'Validée')], default='validee', max_length=10)),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='reservations.reservation')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-cree_le'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='montant_positif')],
            },
        ),
    ]
