# Generated by Django 5.2.18 on 2026-10-09 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefeuille', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='moyen_paiement',
            field=models.CharField(blank=True, choices=[('flooz', 'Flooz (Moov Africa)'), ('mixx', 'Mixx (Togocom)')], help_text='Renseigné pour les mouvements passés par Mobile Money (recharge, retrait).', max_length=10),
        ),
    ]
