# Generated by Django 5.2.18 on 2026-10-08 17:12

import apps.kyc.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycDossier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('type', models.CharField(choices=[('passager', 'Passager'), ('conducteur', 'Conducteur')], max_length=10)),
                ('statut', models.CharField(choices=[('non_verifie', 'Non vérifié'), ('en_attente', 'En attente'), ('verifie', 'Vérifié'), ('rejete', 'Rejeté')], default='non_verifie', max_length=12)),
                ('motif_rejet', models.TextField(blank=True)),
                ('soumis_le', models.DateTimeField(blank=True, null=True)),
                ('traite_le', models.DateTimeField(blank=True, null=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers_kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'dossier KYC',
                'verbose_name_plural': 'dossiers KYC',
                'ordering': ['-cree_le'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycPiece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('type_piece', models.CharField(choices=[('identite', "Pièce d'identité"), ('selfie', 'Selfie'), ('permis', 'Permis de conduire'), ('carte_grise', 'Carte grise'), ('assurance', 'Assurance'), ('photo_vehicule', 'Photo du véhicule')], max_length=20)),
                ('fichier', models.FileField(storage=apps.kyc.models.StockagePrive(), upload_to=apps.kyc.models.chemin_piece)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='kyc.kycdossier')),
            ],
            options={
                'verbose_name': 'pièce KYC',
                'verbose_name_plural': 'pièces KYC',
                'ordering': ['-cree_le'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycConsultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='kyc.kycpiece')),
            ],
            options={
                'verbose_name': 'consultation de pièce KYC',
                'verbose_name_plural': 'consultations de pièces KYC',
                'ordering': ['-cree_le'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='kycdossier',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'type'), name='un_dossier_par_type'),
        ),
        migrations.AddConstraint(
            model_name='kycpiece',
            constraint=models.UniqueConstraint(fields=('dossier', 'type_piece'), name='une_piece_par_type'),
        ),
    ]
